Start adding Material design Components
GoogleCloudPlatform/gcping pull request #84
Opened 2022-01-03 11:57 UTC by saranshdhingra

This PR adds a top bar as per the new design which uses Material Design Components in favour of the currently used Material Design Lite.

Check this for difference: https://material.io/develop/web/guides/migrating-from-mdl

2022-01-03 12:23 UTC, saranshdhingra commented on web/src/index.html
> -    <script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>
Along with this, we should be able to remove the CSS from L:12 once we are done with the material design changes.

2022-01-06 18:32 UTC, enocom commented
@saranshdhingra Mind adding some screenshots to this PR?

2022-01-07 21:19 UTC, crwilcox commented
Can you adjust the colors for the table header and start/stop? I don't think they are in the same palette making this look a bit unfinished.

2022-01-07 22:36 UTC, enocom requested changes
A few visual tweaks:

1. The links in the upper right need some left padding between the text and the icons.
2. GCPing has a favicon. Could we use that as a logo next to the "GCPing" title? It looks a little bare otherwise.
3. The existing site has "Measure your latency to Google Cloud regions" which is dropped here. Can we bring that back?
4. Also, the stop button's teal clashes with the blue. Could we switch the color of the bottom to match the header?
5.

2022-01-10 11:07 UTC, saranshdhingra commented
Thanks @crwilcox @enocom for the color and other gotchas.
Here is the updated design with the logo:
<img width="1437" alt="gcping w/ logo" src="https://user-images.githubusercontent.com/1038319/148755947-89fb067a-f429-489e-9f10-9997d4f29d23.png">

I wanted to try a "white version" of the icon, haven't yet done so. If you think this looks good for now, I'll proceed.

The heading, "Measure your latency to Google Cloud regions" is not like in the design as a lot of elements are not yet there. It should match our internal design in the following PRs.

2022-01-10 16:36 UTC, enocom approved these changes
Looks good to me.

I agree with @crwilcox that the table header color classes with the blue bar. But perhaps we can fix that in the next PR and then deploy when this is all done.

2022-01-10 17:14 UTC, saranshdhingra commented
> Looks good to me.
> 
> I agree with @crwilcox that the table header color classes with the blue bar. But perhaps we can fix that in the next PR and then deploy when this is all done.

I agree, I did change the button, somehow completely missed the table header.
I'll make sure the next PR fixes that as it will mostly be changes to the table component.

2022-01-10 17:14 UTC, merged

2022-01-10 18:48 UTC, crwilcox commented
Agree, not a huge fan of that grey/blue/green header, but the worst bit is resolved. I think we may want to have a palette discussion and go from there. Thanks for getting this in @saranshdhingra