Move control button to the subtitle bar
GoogleCloudPlatform/gcping pull request #85
Opened 2022-01-14 11:34 UTC by saranshdhingra

The PR adds 3 small changes:
- Moves the control button to the subtitle bar as per new design
- Fixes the table's header color as per the `theme primary`.
- Re-adds the logo(somehow missed in the last PR).

Here is the latest view as per this PR:
![image](https://user-images.githubusercontent.com/1038319/149508966-655cba54-6ed0-463a-9de8-cb6a428148a0.png)

2022-01-14 14:22 UTC, enocom submitted a review, later dismissed

2022-01-14 14:22 UTC, enocom commented on web/package.json
> +    "@material/button": "^13.0.0",
Should we be locking dependencies to a version for deterministic builds?

2022-01-14 14:30 UTC, enocom commented
We'll need to verify this looks good on mobile, but that can wait for the final PR in this series and once everything looks good we'll deploy it.

2022-01-14 19:40 UTC, enocom requested changes
Let’s lock to a specific version of dependencies. We can install a bit to upgrade these later.

2022-01-15 15:17 UTC, saranshdhingra commented
> Let’s lock to a specific version of dependencies. We can install a bit to upgrade these later.

Sure thing. Haven't fixed the parcel dependencies, though. I thought, since they are devDependencies, we can be a bit flexible there. Let me know if you want to fix them too, we can do it in the next PR :)

2022-01-15 15:17 UTC, merged

2022-01-18 16:17 UTC, enocom commented
Let's just lock everywhere. Since parcel is building for us, I'm not sure if we have an production dependencies strictly speaking.